name: vsfv-dev

services:
  development-db:
    image: postgres
    restart: unless-stopped
    environment:
      TZ: Europe/Berlin
      POSTGRES_DB: vsf
      POSTGRES_USER: vsf
      POSTGRES_PASSWORD: postgres
    ports:
      - 127.0.0.1:5334:5432
  test-db:
    image: postgres
    restart: unless-stopped
    environment:
      TZ: Europe/Berlin
      POSTGRES_DB: vsf
      POSTGRES_USER: vsf
      POSTGRES_PASSWORD: postgres
    ports:
      - 127.0.0.1:5335:5432
  html2pdf:
    image: improrama/html2pdf-server:v1.2.0
    restart: unless-stopped
    ports:
      - 127.0.0.1:8082:8082
