name: vsfv-test

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      TZ: Europe/Berlin
      POSTGRES_DB: vsf
      POSTGRES_USER: vsf
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - internal
  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    restart: "no"
    environment:
      TZ: Europe/Berlin
      DB_URL: postgresql://vsf:postgres@db:5432/vsf
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ["./node_modules/.bin/prisma"]
    command: ["migrate", "deploy"]
    networks:
      - internal
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env.test
    environment:
      TZ: Europe/Berlin
      HOST: 0.0.0.0
      PORT: 3000
      DB_URL: postgresql://vsf:postgres@db:5432/vsf
      HTML2PDF_URL: http://html2pdf:8082
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
      html2pdf:
        condition: service_started
    ports:
      - 127.0.0.1:3000:3000
    networks:
      - internal
  html2pdf:
    image: improrama/html2pdf-server:v1.2.0
    restart: unless-stopped
    expose:
      - 8082
    networks:
      - internal

networks:
  internal:
