name: "Release"
run-name: "Release"

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        name: Checkout repository

      - name: Login to ${{ vars.REGISTRY_URL }} Docker registry
        run: echo "${{ secrets.REGISTRY_CREDENTIALS }}" | docker login --password-stdin -u "${{ secrets.REGISTRY_USER }}"

      - name: Build Docker image
        run: docker build -t ${{ vars.IMAGE }}:${{ github.ref_name }} .
      
      - name: Tag Docker image
        run: docker tag ${{ vars.IMAGE }}:${{ github.ref_name }} ${{ vars.IMAGE }}:latest

      - name: Push Docker image version
        run: docker push ${{ vars.IMAGE }}:${{ github.ref_name }}
      
      - name: Push Docker image latest
        run: docker push ${{ vars.IMAGE }}:latest

      - name: Logout from ${{ vars.REGISTRY_URL }} Docker registry
        run: docker logout
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - build
    steps:
      - uses: softprops/action-gh-release@v2
        name: Create GitHub Release
        with:
          body: |
            Docker image: `${{ vars.IMAGE }}:${{ github.ref_name }}`
          tag_name: ${{ github.ref_name }}